# Generated by Django 3.1.3 on 2020-12-16 18:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='A_level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('date_acquired', models.DateField(default=datetime.date(2012, 7, 1))),
                ('grade', models.CharField(choices=[('A*', 'A*'), ('A', 'A')], max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GCSE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('date_acquired', models.DateField(default=datetime.date(2010, 7, 1))),
                ('grade', models.CharField(choices=[('A*', 'A*'), ('A', 'A'), ('B', 'B')], max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Thesis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_acquired', models.DateField()),
                ('subject', models.CharField(max_length=50)),
                ('grade', models.CharField(max_length=50)),
                ('title', models.CharField(choices=[('MSc', 'MSc'), ('BA', 'BA')], max_length=50)),
                ('university', models.CharField(max_length=50)),
                ('thesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainSite.thesis')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
