# Generated by Django 3.1.3 on 2021-01-26 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0002_auto_20210125_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thesis',
            name='url',
        ),
        migrations.AddField(
            model_name='thesis',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='theses'),
        ),
    ]
