# Generated by Django 3.1.3 on 2021-01-27 18:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0004_auto_20210127_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesis',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='theses/<django.db.models.fields.UUIDField>/'),
        ),
    ]
