# Generated by Django 3.1.3 on 2021-01-27 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0005_auto_20210127_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesis',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='theses/Cast(F(uuid))/'),
        ),
    ]
