# Generated by Django 3.1.3 on 2021-01-27 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0006_auto_20210127_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesis',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='theses/Cast(Value(<django.db.models.fields.UUIDField>))/'),
        ),
    ]
