# Generated by Django 3.1.3 on 2021-02-04 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0009_auto_20210128_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ_Question_Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.CharField(max_length=100)),
                ('Answer', models.TextField()),
            ],
        ),
    ]
