# Generated by Django 3.1.3 on 2021-02-04 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0010_faq_question_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coursera_Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('grade', models.CharField(max_length=50)),
                ('verification_link', models.TextField(null=True)),
                ('date_acquired', models.DateField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
