# Generated by Django 3.1.3 on 2021-02-04 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0011_coursera_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursera_course',
            name='grade',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
